name: flugx_cli
description: Flugx is a CLI tool that automatically generates a complete Flutter package called `app_api` using GetX, based on a Swagger/OpenAPI specification file.
version: 1.0.0+2
homepage: https://github.com/KalybosPro/flux
repository: https://github.com/KalybosPro/flux
issue_tracker: https://github.com/KalybosPro/flux/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.4.1
  analyzer: ^5.12.0
  path: ^1.8.3
  dart_style: ^2.2.4
  json_annotation: ^4.9.0
  yaml: ^3.1.3
  universal_io: ^2.2.2
  http: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^5.0.0
  remove_from_coverage: ^2.0.0
  test: ^1.24.0

executables:
  flugx: flugx

flutter:
  platform:
    Android:
    iOS:
    Windows:
    Linux:
    macOS:
    Web:
