/// {@template env}
/// A Very Good Package generated by Env Builder CLI.
/// {@endtemplate}
enum Env {
  /// The value for Base Url.
  baseUrl('BASE_URL'),

  /// The value for Results Url.
  resultsUrl('RESULTS_URL');

  /// {@macro env}
  const Env(this.name);

  /// The value of the enum class
  final String name;
}

/// Env value signature that can be used to get an environment value, base
/// on provided [Env].
typedef EnvValue = String Function(Env env);
